{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "self-learning-platform.fullname" . }}
  labels:
    {{- include "self-learning-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "self-learning-platform.selectorLabels" . | nindent 6 }}
  {{- with .Values.networkPolicy.policyTypes }}
  policyTypes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
