{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "self-learning-platform.fullname" $ }}-{{ .name }}
  labels:
    {{- include "self-learning-platform.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .data }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
