apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-learning-platform.fullname" . }}
  labels:
    {{- include "self-learning-platform.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
      {{- if .Values.service.appProtocol }}
      appProtocol: {{ .Values.service.appProtocol }}
      {{- end }}
    {{- range $port := .Values.service.extraPorts }}
    - port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
      {{- if $port.appProtocol }}
      appProtocol: {{ $port.appProtocol }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "self-learning-platform.selectorLabels" . | nindent 4 }}
